runtime: python311
default_expiration: 0

#uncomment these lines if longer timeout (>10mins) needed 
#instance_class: B4
#basic_scaling:
#  max_instances: 1

instance_class: F4
automatic_scaling:
  min_instances: 0
  max_instances: 1

# instance classes and free tier quotas (don't forget to adjust gunicorn's --workers flag):
#   F1: 256MB / 600MHz - 28 free hours per day (default)
#   F2: 512MB / 1.2GHz - 14 free hours per day
#   F4: 1024MB / 2.4GHz - 7 free hours per day
#   B1: 256MB / 600MHz - 9 free hours per day
#   B2: 512MB / 1.2GHz - 4:30 free hours per day (default)
#   B4: 1024MB / 2.4GHz - 2:15 free hours per day
# request timeout:
#   F - 10 minutes
#   B - 24 hours
app_engine_apis: true

env_variables:
  CONFIG: gs://$PROJECT_ID/remarque/config.json
  GIT_COMMIT: cc3220bb185d821d2deba14235ad099a3a11a294
  LOG_LEVEL: DEBUG
  PYTHONPATH: server

entrypoint: gunicorn -b :$PORT server:app --timeout 0 --workers 2
